apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: demo-pool
  namespace: default
spec:
  addresses:
  - 172.19.0.100-172.19.0.110
  
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: default
spec:
  ipAddressPools:
  - demo-pool